---
openapi: 3.0.1
info:
  title: API V1
  version: v1
servers:
- url: http://localhost:3000
components:
  parameters:
    doctor_id:
      name: doctor_id
      in: path
      required: true
      schema:
        type: integer
        format: int64
        example: 1
    patient_id:
      name: patient_id
      in: path
      required: true
      schema:
        type: integer
        format: int64
        example: 1
  schemas:
    Doctor:
      type: object
      required:
      - id
      - first_name
      - last_name
      properties:
        id:
          type: integer
          format: int64
          example: 1
          readOnly: true
        first_name:
          type: string
          example: Иван
        last_name:
          type: string
          example: Иванов
        middle_name:
          type: string
          example: Иванович
    Patient:
      type: object
      required:
      - id
      - first_name
      - last_name
      - birthday
      - gender
      properties:
        id:
          type: integer
          format: int64
          example: 10
          readOnly: true
        first_name:
          type: string
          example: Петр
        last_name:
          type: string
          example: Петров
        middle_name:
          type: string
          example: Петрович
        birthday:
          type: string
          format: date
          example: '1990-01-01'
        gender:
          type: boolean
          description: 'Пол пациента: true = мужской, false = женский'
          example: true
        height:
          type: integer
          example: 180
        weight:
          type: integer
          example: 75
        doctor_ids:
          type: array
          items:
            type: integer
          description: "Список ID лечащих врачей"
          example: []
        created_at:
          type: string
          format: date-time
          readOnly: true
          example: '2025-09-26T22:56:19Z'
        updated_at:
          type: string
          format: date-time
          readOnly: true
          example: '2025-09-26T22:56:19Z'
paths:
  "/api/v1/doctors":
    get:
      summary: Список докторов
      tags:
      - doctors
      parameters:
      - name: limit
        in: query
        description: Лимит на количество записей
        schema:
          type: integer
      - name: offset
        in: query
        description: Смещение для пагинации
        schema:
          type: integer
      responses:
        '200':
          description: Список врачей
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Doctor"
    post:
      summary: Создать доктора
      tags:
        - doctors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                doctor:
                  type: object
                  properties:
                    first_name:
                      type: string
                      example: Иван
                    middle_name:
                      type: string
                      example: Иванович
                    last_name:
                      type: string
                      example: Петров
                  required:
                    - first_name
                    - last_name
      responses:
        '201':
          description: Доктор создан
          content:
            application/json:
              schema:
                type: object
                properties:
                  doctor:
                    $ref: "#/components/schemas/Doctor"
        '422':
          description: Некорректные данные
  "/api/v1/doctors/{doctor_id}":
    parameters:
    - name: doctor_id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Показать доктора
      tags:
      - doctors
      responses:
        '200':
          description: Врач найден
        '404':
          description: Врач не найден
    patch:
      summary: Обновить доктора
      tags:
      - doctors
      parameters: []
      responses:
        '200':
          description: Врач обновлён
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Doctor"
    delete:
      summary: Удалить доктора
      tags:
      - doctors
      responses:
        '204':
          description: Врач удалён
        '404':
          description: Врач не найден
  "/api/v1/patients":
    get:
      summary: Список пациентов
      tags:
      - patients
      parameters:
      - name: full_name
        in: query
        description: Фильтр по полному имени
        schema:
          type: string
      - name: gender
        in: query
        description: Фильтр по полу
        schema:
          type: boolean
      - name: start_age
        in: query
        description: Минимальный возраст
        schema:
          type: integer
      - name: end_age
        in: query
        description: Максимальный возраст
        schema:
          type: integer
      - name: limit
        in: query
        description: Лимит на количество записей
        schema:
          type: integer
      - name: offset
        in: query
        description: Смещение для пагинации
        schema:
          type: integer
      responses:
        '200':
          description: Список пациентов
          content:
            application/json:
              schema:
                type: object
                properties:
                  patients:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Patient"
    post:
      summary: Создать пациента
      tags:
        - patients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                patient:
                  $ref: "#/components/schemas/Patient"
      responses:
        '201':
          description: Пациент создан
        '422':
          description: Некорректные данные
  "/api/v1/patients/{patient_id}":
    get:
      summary: Показать пациента
      tags:
      - patients
      parameters:
      - name: patient_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Пациент найден
        '404':
          description: Пациент не найден
    patch:
      summary: Обновить пациента
      tags:
        - patients
      parameters:
        - name: patient_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                patient:
                  $ref: "#/components/schemas/Patient"
      responses:
        '200':
          description: Пациент обновлён
        '422':
          description: Некорректные данные
    delete:
      summary: Удалить пациента
      tags:
      - patients
      parameters:
      - name: patient_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Пациент удалён
        '404':
          description: Пациент не найден
  "/api/v1/patients/{patient_id}/calculate_bmr":
    post:
      summary: Рассчитать BMR
      tags:
      - patients
      parameters:
      - name: patient_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: Рассчёт выполнен и сохранён
        '422':
          description: Некорректные данные
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                formula:
                  type: string
                  enum:
                  - mifflin
                  - harris
                  description: 'Выберите формулу: mifflin – Миффлина–Сан Жеора, harris
                    – Харриса–Бенедикта'
                  example: mifflin/harris
              required:
              - formula
  "/api/v1/patients/{patient_id}/bmr_history":
    get:
      summary: История расчетов BMR
      tags:
      - patients
      parameters:
      - name: patient_id
        in: path
        required: true
        schema:
          type: integer
      - name: limit
        in: query
        description: Лимит на количество записей
        schema:
          type: integer
      - name: offset
        in: query
        description: Смещение для пагинации
        schema:
          type: integer
      responses:
        '200':
          description: История расчетов BMR
        '404':
          description: Пациент не найден
  "/api/v1/patients/{patient_id}/calculate_bmi":
    get:
      summary: Рассчитать BMI через внешний API
      tags:
      - patients
      parameters:
      - name: patient_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Успешный расчёт BMI
        '422':
          description: Нет данных для веса/роста
        '404':
          description: Пациент не найден
